# Generated by Django 3.1.6 on 2021-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banknifty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('signal', models.TextField(max_length=100)),
                ('entry', models.TextField(max_length=100)),
                ('target', models.TextField(max_length=100)),
                ('advisory', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='nifty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('signal', models.TextField(max_length=100)),
                ('entry', models.TextField(max_length=100)),
                ('target', models.TextField(max_length=100)),
                ('advisory', models.TextField(max_length=500)),
            ],
        ),
    ]
