# Generated by Django 3.1.6 on 2021-05-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0005_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='members',
        ),
    ]
