# Generated by Django 3.1.6 on 2021-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0006_auto_20210505_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='membership',
            field=models.CharField(choices=[('1', 'Trial'), ('2', 'Premium')], default='Trial', max_length=20),
        ),
    ]
