# Generated by Django 3.1.6 on 2021-05-05 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0007_members_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='joinedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='membership',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Premium', 'Premium')], default='Trial', max_length=20),
        ),
    ]
