# Generated by Django 3.1.6 on 2021-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0008_auto_20210505_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='subscriptionenddate',
            field=models.DateTimeField(default=None),
        ),
    ]
