# Generated by Django 3.1.6 on 2021-05-05 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0009_members_subscriptionenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='status',
            field=models.CharField(default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='subscriptionenddate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
